name: CI - Backend Tests + Android APK Build (Release)

on:
  pull_request:

jobs:

  backend-tests:
    name: Testes do Backend (Node)
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: tasksdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend deps
        working-directory: backend
        run: npm install

      - name: Run backend tests
        working-directory: backend
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASS: root
          DB_NAME: tasksdb
        run: npm test



  build-android:
    name: Build APK Release Android
    needs: backend-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---- Java 17 ----
      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # ---- Android SDK ----
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses

      - name: Install Android Build Tools + NDK
        run: |
          sdkmanager "platform-tools" \
                     "platforms;android-34" \
                     "build-tools;34.0.0" \
                     "ndk;26.1.10909125"

      # ---- Node 20 (fix metro toReversed error) ----
      - name: Setup Node (Node 20 required for Metro)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ---- Install React Native deps ----
      - name: Install mobile deps
        working-directory: mobile
        run: npm install

      - name: Grant Gradle permissions
        run: chmod +x mobile/android/gradlew

      # ---- Build Release APK ----
      - name: Build Release APK
        working-directory: mobile/android
        env:
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/26.1.10909125
        run: ./gradlew assembleRelease --stacktrace

      # ---- Upload Artifact ----
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: TaskSync-release.apk
          path: mobile/android/app/build/outputs/apk/release/app-release.apk
